# Generated by Django 2.0.7 on 2018-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_settings_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedBook',
            fields=[
                ('book_id', models.IntegerField(default=False)),
                ('file_type', models.CharField(default=False, max_length=4)),
                ('file_id', models.CharField(default=False, max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
