# Generated by Django 2.0.7 on 2018-07-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_postedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
