# Generated by Django 2.0.7 on 2018-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20180714_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
