# Generated by Django 2.2.4 on 2019-09-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20180716_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='allow_ru',
            field=models.BooleanField(default=True),
        ),
    ]
